### ISSUE TITLE
Use of LLVM is not specified

### ISSUE THREAD

**Issue by L-TChen** [AndrasKovacs/dynamic-array#1]
## Problem

The use of LLVM is not specified in the doc, so running `stack build` emits the following error message on a machine without LLVM found in path:

```
Building library for dynamic-array-0.1.2.0..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [10 and 15)
[1 of 3] Compiling Data.Array.Dynamic.L
...
```

## Proposals
1. Add `llvm` as a requirement explicitly.
2. Add a flag `llvm` so that llvm becomes optional. Adding the following to `package.yaml` should work. 
```
flags:
  llvm:
    description: use llvm for codegen
    default: false
    manual: true
...
when:
  - condition: flag(llvm)
    ghc-options:
      - -fllvm
```

My main concern for the second proposal is that `stack` does not seem to pass flags for dependencies. I tried compiling `smalltt` with this flag added, but building `smalltt` with `--flag dynamic-array:llvm` without `llvm` found in path does not cause any problem.

Environment:
- macOS 14.0
- stack 2.13.1
- GHC 9.4.7
